import "./globals.css";

import { ThemeProvider } from "next-themes";

import { Inter } from "next/font/google";

// COMPONENTS
import Navbar from "../components/Header/Navbar";
import Banner from "../components/Header/Banner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider attribute="class">
          <Banner />
          <Navbar />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
